# Generated by Django 3.1.5 on 2021-03-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_1', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_2', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_3', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_4', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_5', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_6', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_7', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_8', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_9', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_10', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_11', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_12', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_13', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_14', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_15', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_16', models.CharField(blank=True, max_length=100, null=True)),
                ('symptom_17', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'symptoms',
            },
        ),
    ]
