# Generated by Django 3.1.5 on 2021-03-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_question', models.CharField(blank=True, max_length=100, null=True)),
                ('prev_answer', models.IntegerField()),
                ('question', models.CharField(blank=True, max_length=100, null=True)),
                ('button1', models.CharField(blank=True, max_length=50, null=True)),
                ('button2', models.CharField(blank=True, max_length=50, null=True)),
                ('button3', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
