# Generated by Django 3.1.5 on 2021-03-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='button3',
        ),
        migrations.AddField(
            model_name='questions',
            name='button0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
