# Generated by Django 3.1.5 on 2021-03-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_auto_20210328_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='button0',
            new_name='btn0Text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='button1',
            new_name='btn1Text',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='button2',
            new_name='btn2Text',
        ),
    ]
