# Generated by Django 3.1.5 on 2021-03-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0004_auto_20210329_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='btn0UserText',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='btn1UserText',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='btn2UserText',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
