# Generated by Django 3.1.5 on 2021-04-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_auto_20210329_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='prev_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
