# Generated by Django 3.1.5 on 2021-04-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0007_auto_20210405_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='prev_question',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
