# Generated by Django 3.1.5 on 2021-04-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0008_auto_20210405_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='add_symptom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
