# Generated by Django 3.1.5 on 2021-04-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0009_questions_add_symptom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='add_symptom',
            new_name='check_symptom',
        ),
    ]
