# Generated by Django 3.1.5 on 2021-04-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0010_auto_20210421_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='check_symptom',
            new_name='checkSymptom',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='prev_answer',
            new_name='prevAnswer',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='prev_question',
            new_name='prevQuestion',
        ),
    ]
